### ISSUE TITLE
Rendering problem with Markdown

### ISSUE THREAD

**Issue by SamirPS** [awsdocs/amazon-ecr-public-user-guide#4]
Greetings,

I have a query regarding the description of my ECR repository. While browsing through https://docs.aws.amazon.com/AmazonECR/latest/public/public-repository-edit.html, I noticed that ECR use the GitHub Flavored Markdown format. I would like to add the following code:

```
[![LTS](https://assets.ubuntu.com/v1/0a5ff561-LTS%402x.png?h=17)](https://gallery.ecr.aws/lts/ubuntu) until date
```

This code displays well on Github and allows users to click on the image check here https://github.com/SamirPS/Markowntest. However, on ECR, only the text appears on the first line of the table, and the image is not displayed see https://gallery.ecr.aws/ubuntu/ubuntu.

I'd like to know whether ECR uses a different markdown version than Github or if this is a bug.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
